"""Orchestrates one target -> report run, emitting progress events as it goes.

Multi-agent hooks into progress (brief F5/F10): each pipeline stage calls
`on_progress` with a stage name and status before/after doing its work, which
the API layer forwards as Server-Sent Events to the input UI's progress
indicator.

Two stages (interpretation_swarm / section_graph) are currently blocked: real
Bedrock Claude access is unavailable for this AWS account pending the
Anthropic use-case form (see DECISION_LOG.md, 2026-09-11). Those stages emit
an honest "pending" progress event and the report renders with a visible
placeholder in the affected sections -- never a fabricated result standing in
for a blocked one.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Callable, Optional

from backend.citation_ledger import CitationLedger
from backend.genetics_precedent import get_precedent
from backend.grounding_score import highlight_html, score_claim
from backend.openfda_client import gather_evidence_for_drugs
from backend.report_renderer import EvaluationScore, Report, ReportSection
from backend.target_resolution import resolve_target

ProgressCallback = Callable[[str, str, Optional[str]], None]  # (stage, status, detail)

PENDING_NOTE = (
    "[PENDING -- blocked on Bedrock Anthropic model access for this AWS account; "
    "see DECISION_LOG.md 2026-09-11] This section is generated by a Strands agent "
    "that could not be exercised in this run."
)


def _noop_progress(stage: str, status: str, detail: Optional[str] = None) -> None:
    return None


@dataclass
class PipelineResult:
    report: Report
    target_resolution: object
    is_partial: bool  # True while any LLM-dependent stage is pending


def run_pipeline(target: str, on_progress: ProgressCallback = _noop_progress) -> PipelineResult:
    ledger = CitationLedger()
    is_partial = False

    on_progress("target_resolution", "running", None)
    resolution = resolve_target(target)
    if not resolution.found:
        on_progress("target_resolution", "empty", f"no drug names resolved for '{target}'")
        report = Report(
            target=target,
            generated_at=datetime.now(timezone.utc).isoformat(),
            sections=[
                ReportSection(
                    1,
                    "Target Profile & Biological Function",
                    f"<p><strong>No evidence found.</strong> Search path: "
                    f"{[a.path for a in resolution.search_trail]}, 0 hits, "
                    f"retrieved {resolution.searched_at}.</p>",
                )
            ],
            ledger=ledger,
            data_source_note="No drug names resolved for this target -- see Section 1 for the attempted search path.",
        )
        return PipelineResult(report=report, target_resolution=resolution, is_partial=False)
    on_progress("target_resolution", "done", f"{len(resolution.drug_names)} drug name(s) resolved")

    on_progress("evidence_retrieval", "running", None)
    evidence = gather_evidence_for_drugs(resolution.drug_names)
    label_refs: list[str] = []
    nonclinical_excerpts: list[str] = []
    for item in evidence:
        if item.label.source_status in ("live", "cached") and item.label.nonclinical_toxicology:
            ref = ledger.register(
                source_type="label",
                title=f"{item.label.drug_name} label -- Nonclinical Toxicology",
                url=item.label.source_url,
                application_number=item.label.application_number,
            )
            label_refs.append(ref)
            nonclinical_excerpts.append(" ".join(item.label.nonclinical_toxicology))
    on_progress("evidence_retrieval", "done", f"{len(label_refs)} label source(s) registered")

    on_progress("genetics_precedent", "running", None)
    precedent = get_precedent(target)
    genetics_ref = None
    if precedent:
        genetics_ref = ledger.register(
            source_type="curated",
            title="Curated knockout-precedent dataset",
            url=f"internal://genetics-precedent/{target}",
            curated=True,
        )
    on_progress("genetics_precedent", "done" if precedent else "empty", None)

    on_progress("interpretation_swarm", "pending", "blocked on Bedrock Anthropic access")
    on_progress("section_graph", "pending", "blocked on Bedrock Anthropic access")
    on_progress("evaluations", "pending", "depends on section_graph output")
    is_partial = True

    section1_body = (
        f"<p>{len(resolution.drug_names)} approved drug(s) resolved via "
        f"{resolution.resolution_path.replace('_', ' ')}.</p><p>{PENDING_NOTE}</p>"
    )

    if precedent and genetics_ref:
        section2_body = (
            f"<p>{precedent.phenotype_summary} "
            f'<a class="ref-link" href="#ref-{genetics_ref}">[{genetics_ref}]</a></p>'
            f"<p><em>{precedent.relevance_to_target_safety}</em></p>"
        )
    else:
        section2_body = (
            "<p><strong>No curated knockout-precedent entry for this target.</strong> "
            f"Search path: internal curated dataset, 0 hits.</p><p>{PENDING_NOTE}</p>"
        )

    example_grounding_html = ""
    if nonclinical_excerpts and label_refs:
        sample_claim = nonclinical_excerpts[0][:200]
        grounding = score_claim(sample_claim, nonclinical_excerpts[0])
        example_grounding_html = (
            f'<p>{highlight_html(sample_claim, grounding)} '
            f'<a class="ref-link" href="#ref-{label_refs[0]}">[{label_refs[0]}]</a> '
            f"(grounding {grounding.score:.2f})</p>"
        )

    sections = [
        ReportSection(1, "Target Profile & Biological Function", section1_body),
        ReportSection(2, "Genetic & Knockout Precedent", section2_body),
        ReportSection(3, "Class Effects & Known Target Toxicities", f"<p>{PENDING_NOTE}</p>"),
        ReportSection(4, "Regulatory & Clinical Precedents", f"<p>{PENDING_NOTE}</p>"),
        ReportSection(
            5,
            "Adversity & Evidence Weight Analysis",
            example_grounding_html + f"<p>{PENDING_NOTE}</p>",
        ),
        ReportSection(6, "Nonclinical Safety Recommendations & CTD-M2.4-Bridge", f"<p>{PENDING_NOTE}</p>"),
        ReportSection(7, "References & Regulatory Sources", ""),  # renderer fills from ledger
    ]

    report = Report(
        target=target,
        generated_at=datetime.now(timezone.utc).isoformat(),
        sections=sections,
        ledger=ledger,
        interpretation_cards=[],
        evaluation_scores=[
            EvaluationScore("Builtin.Faithfulness", 0.0, "gap"),
            EvaluationScore("Builtin.Correctness", 0.0, "gap"),
        ],
        data_source_note=(
            "PARTIAL RUN: interpretation swarm and section graph are pending -- "
            "Bedrock Anthropic access unavailable for this account."
        )
        if is_partial
        else None,
    )
    on_progress("report_render", "done", None)
    return PipelineResult(report=report, target_resolution=resolution, is_partial=is_partial)
